In [20]:
import torch
import torchvision
import torchvision.transforms as transforms
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.autograd import Variable
import numpy as np

In [21]:
base = torch.tensor([[0, 1],[2, 3]])
base.is_contiguous()

True

In [22]:
base

tensor([[0, 1],
        [2, 3]])

In [23]:
t = base.transpose(0, 1)

In [24]:
t

tensor([[0, 2],
        [1, 3]])

In [25]:
base.is_contiguous()

True

In [26]:
# View tensors might be non-contiguous.
t.is_contiguous()

False

In [27]:
# To get a contiguous tensor, call `.contiguous()` to enforce
# copying data when `t` is not contiguous.
c =  t.contiguous()

In [28]:
c.is_contiguous()

True

# AUTOGRAD MECHANICS

In [29]:
import torch 

a = torch.randn((3,3), requires_grad = True)

w1 = torch.randn((3,3), requires_grad = True)
w2 = torch.randn((3,3), requires_grad = True)
w3 = torch.randn((3,3), requires_grad = True)
w4 = torch.randn((3,3), requires_grad = True)

b = w1*a 
c = w2*a

d = w3*b + w4*c 

L = 10 - d

print("The grad fn for a is", a.grad_fn)
print("The grad fn for d is", d.grad_fn)

The grad fn for a is None
The grad fn for d is <AddBackward0 object at 0x0000014F5BF6F160>


In [30]:
(a-3).sum()

tensor(-26.9851, grad_fn=<SumBackward0>)

In [31]:
a

tensor([[ 0.7244,  0.0442,  0.3621],
        [-0.9065,  0.1668, -0.8544],
        [-0.2372,  0.9518, -0.2362]], requires_grad=True)

# requires_grad_() function

Scalar : int, float
Non-scalar : matrix

Scalar type

In [32]:
x = torch.tensor(np.array([[1, 2, 3], [4, 5, 6]]).astype(np.float), requires_grad = True)

In [33]:
y = torch.ones(2,3)

In [34]:
y

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [35]:
z = x + y 

In [36]:
z.requires_grad

True

In [37]:
# It show errors because matrix is non-scalar type
# z.backward()

non-scalar type

In [38]:
x = torch.tensor(np.array([2]).astype(np.float), requires_grad = True)

In [39]:
x.requires_grad

True

In [40]:
y = torch.ones(1)

In [41]:
y

tensor([1.])

In [42]:
z = x + 2*y

In [43]:
z.requires_grad

True

In [44]:
z.backward()

In [45]:
z

tensor([4.], dtype=torch.float64, grad_fn=<AddBackward0>)

In [46]:
x.grad

tensor([1.], dtype=torch.float64)

In [47]:
y.grad == None

True

In [48]:
z.grad

c:\users\tkdang\google drive\lecture_ai\10.deep learning\.venv\lib\site-packages\ipykernel_launcher.py:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the gradient for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations.
  """Entry point for launching an IPython kernel.


.data and .detach

In [49]:
a = torch.tensor([1,2,3.], requires_grad = True)

In [50]:
out = a.sigmoid()

In [51]:
c = out.detach()

In [52]:
c

tensor([0.7311, 0.8808, 0.9526])

In [53]:
out

tensor([0.7311, 0.8808, 0.9526], grad_fn=<SigmoidBackward>)

In [54]:
out.sum().backward()

In [55]:
a.grad

tensor([0.1966, 0.1050, 0.0452])

In [56]:
out

tensor([0.7311, 0.8808, 0.9526], grad_fn=<SigmoidBackward>)

In [57]:
out.sum().backward(retain_graph = True) == None

RuntimeError: Trying to backward through the graph a second time, but the saved intermediate results have already been freed. Specify retain_graph=True when calling backward the first time.

In [ ]:
out

In [ ]:
out.sum().backward()

# Accumulating losses

In [ ]:
torch.cuda.current_device()

In [ ]:
torch.device('cuda')

In [ ]:
i = torch.LongTensor([[0, 2], [1, 0], [1, 2]])


In [ ]:
i.t()

In [ ]:
v = torch.FloatTensor([3,      4,      5    ])

In [ ]:
torch.sparse.FloatTensor(i.t(), v, torch.Size([2,3])).to_dense()

In [ ]:
torch.sparse.FloatTensor(i.t(), v, torch.Size([2,3])).to_dense()

# Test view function

In [58]:
t = torch.rand(4, 4)
b = t.view(2, 8)

In [59]:
t

tensor([[0.4556, 0.6125, 0.7609, 0.1540],
        [0.0500, 0.4583, 0.1509, 0.0520],
        [0.2148, 0.8675, 0.9237, 0.9325],
        [0.3549, 0.4942, 0.7977, 0.0591]])

In [60]:
b

tensor([[0.4556, 0.6125, 0.7609, 0.1540, 0.0500, 0.4583, 0.1509, 0.0520],
        [0.2148, 0.8675, 0.9237, 0.9325, 0.3549, 0.4942, 0.7977, 0.0591]])

In [62]:
flat = t.view(-1, 16)

In [63]:
flat

tensor([[0.4556, 0.6125, 0.7609, 0.1540, 0.0500, 0.4583, 0.1509, 0.0520, 0.2148,
         0.8675, 0.9237, 0.9325, 0.3549, 0.4942, 0.7977, 0.0591]])